# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'processview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProcessViewDialog(object):
    def setupUi(self, ProcessViewDialog):
        ProcessViewDialog.setObjectName("ProcessViewDialog")
        ProcessViewDialog.resize(442, 512)
        ProcessViewDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProcessViewDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.process_table = QtWidgets.QTableView(ProcessViewDialog)
        self.process_table.setAlternatingRowColors(True)
        self.process_table.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection)
        self.process_table.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.process_table.setSortingEnabled(True)
        self.process_table.setObjectName("process_table")
        self.verticalLayout.addWidget(self.process_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.attach_button = QtWidgets.QPushButton(ProcessViewDialog)
        self.attach_button.setObjectName("attach_button")
        self.horizontalLayout.addWidget(self.attach_button)
        self.cancel_button = QtWidgets.QPushButton(ProcessViewDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ProcessViewDialog)
        QtCore.QMetaObject.connectSlotsByName(ProcessViewDialog)

    def retranslateUi(self, ProcessViewDialog):
        _translate = QtCore.QCoreApplication.translate
        ProcessViewDialog.setWindowTitle(
            _translate("ProcessViewDialog", "Dialog"))
        self.attach_button.setText(_translate("ProcessViewDialog", "Attach"))
        self.cancel_button.setText(_translate("ProcessViewDialog", "Cancel"))
